### ISSUE TITLE
Unable to get the packs working on 1.20.1

### ISSUE THREAD

**Issue by DraconicNEO** [MopsTMC/C4Music#1]
I tried using the packs on 1.20.1 but they didn't work. Said it wasn't compatible and when I used it anyway it made the game totally silent except on the main menu where music played fine.

**Comment by MopsTMC** [comment]
Hello, I haven't had any issues using any of the packs in 1.20.1, at least the main one which I assume you are using the latest version of. When you accept the incompatibility warning does the game stop outputing any kind of audio or is it only the music that doesn't play? Are you using any other resource packs or mods that could interfere?
Try running `/playsound minecraft:music.game music @s` inside a world if music is the only thing you can't hear.

**Comment by MopsTMC** [comment]
Unfortunately I need more details on your game configuration (mods, resource packs, settings) as I'm able to use the resource packs (C4Music v3.0 + C4Nether v1) normally on 1.20.1 (with Simply Optimised). Since I don't know your game configuration it's up to you to investigate by ruling out resource packs and mods that could be interfering with the game's **music scheduler** or **track list** which seems to be the case here. In the resource pack's main page I have a detailed list and descriptions of compatibility with some mods and packs found on modrinth.

**Comment by DraconicNEO** [comment]
> Unfortunately I need more details on your game configuration (mods, resource packs, settings) as I'm able to use the resource packs (C4Music v3.0 + C4Nether v1) normally on 1.20.1 (with Simply Optimised). Since I don't know your game configuration it's up to you to investigate by ruling out resource packs and mods that could be interfering with the game's **music scheduler** or **track list** which seems to be the case here. In the resource pack's main page I have a detailed list and descriptions of compatibility with some mods and packs found on modrinth.

I have Forge installed with No-chat-reports but no other mods than that. I have [Faithful32x](https://faithfulpack.net/) and [NoPumpkinBlur](https://www.planetminecraft.com/texture-pack/invisible-pumpkin-blur-4981714/)

Packs are loaded in the following order:
- C4Nether
- C4Music
- InvisiblePumpkinBlur
- Faithful32X

**Comment by Billnotic** [comment]
The pack doesn't appear to work on 1.20.1 for me either. I am running no other music mods or packs that change the new music, and all music still plays however new music is not replaced.

**Comment by DraconicNEO** [comment]
Resolved, Pack has since started working, forgot to close the issue. Sorry about that.
