### ISSUE TITLE
Vanilla music paths are outdated/incorrect as of 1.20.3, causing them to be skipped

### ISSUE THREAD

**Issue by krazybluemonkey** [MopsTMC/C4Music#2]
after pouring a few hours into trying to fix the new tracks playing too often, i believe i found the problem and solution. after looking at music packs that did work, i found probably the only mention of this affecting anyone else's pack: https://modrinth.com/resourcepack/cornbreads-music-fixer/version/1.1.1 
so a path like `music/game/calm1` is now `music/game/minecraft`. all the new filenames can be found here: https://minecraft.wiki/w/Sounds.json#Java_Edition_values

**Comment by MopsTMC** [comment]
Oh wow, thanks for bringing this up and putting the effort into investigating! I didn't see this in any changelogs and I'm surprised why mojang even messed with this. ~~I will probably release a patch in addon form since this isn't really worth a reupload and I don't want to break compatibility with previous versions.~~ I completely forgot about pack overlays, thanks for giving the inspiration.

**Comment by MopsTMC** [comment]
New release https://modrinth.com/resourcepack/c4music/version/3.1. Thanks for opening this issue!
