### ISSUE TITLE
How would I extract the resorce pack to a folder

### ISSUE THREAD

**Issue by gitdrug** [MopsTMC/C4Music#4]
I want to add calm4 to the resource pack but cant since you prevent extraction

**Comment by MopsTMC** [comment]
I prevent extraction as an effort to abide by C418's usage policy and in order to be able to host it on Modrinth. As I mention in the readme the structure of the resource pack in its entirety is available on this repo, only missing the audio files, so you can append to it. You could also leave a recommendation if you'd like to see a feature officially in the resource pack
